version: '3'
services:
  #======================================================================  python3  ======
  anaconda:
    build:
      context: ./python
      args:
        - ENV=${ENV}
    working_dir: /opt/flask
    # command: flask run
    entrypoint: uwsgi --http 0.0.0.0:5000  --wsgi-file /opt/flask/app.py --callable app
    # restart: always
    tty: true
    ports:
     - 8888:8888
     - 5000:5000
    volumes:
      - ./python/flask:/opt/flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
