FROM nginx:1.19
# COPY ./default.conf /etc/nginx/conf.d/default.conf
# COPY ./uwsgi_params /etc/nginx/uwsgi_params # already exist?
COPY ssl/server.crt /etc/nginx/server.crt
COPY ssl/server.key /etc/nginx/server.key
RUN mkdir /var/run/uwsgi

WORKDIR /etc/nginx
RUN chmod 400 /etc/nginx/server.crt
RUN chown root:root /etc/nginx/server.crt
CMD ["nginx", "-g", "daemon off;"]